# Generated by Django 4.2.5 on 2023-09-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_giveaway", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="askforbookrequest", name="is_confirmed",),
        migrations.AddField(
            model_name="askforbookrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "PENDING"),
                    ("Accepted", "ACCEPTED"),
                    ("Declined", "DECLINED"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
