# Generated by Django 4.2.5 on 2023-09-30 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_supporting_resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="condition",
            name="condition",
            field=models.CharField(
                choices=[("New", "NEW"), ("Used", "USED")],
                default="New",
                max_length=255,
            ),
        ),
    ]
